#if !os(macOS)
import XCTest

extension DirectoryTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectoryTests = [
        ("testChangeWorkingDirectory", testChangeWorkingDirectory),
        ("testContents", testContents),
        ("testCreate", testCreate),
        ("testCreateIntermediate", testCreateIntermediate),
        ("testCurrent", testCurrent),
        ("testDescription", testDescription),
        ("testExist", testExist),
        ("testInitFromString", testInitFromString),
        ("testLocation", testLocation),
        ("testName", testName),
        ("testPath", testPath),
        ("testRemove", testRemove),
        ("testRemoveWithContent", testRemoveWithContent),
    ]
}

extension FileLoggerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileLoggerTests = [
        ("testFileLogger", testFileLogger),
    ]
}

extension FileTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileTests = [
        ("testCreateExists", testCreateExists),
        ("testDescription", testDescription),
        ("testInit", testInit),
        ("testInitPath", testInitPath),
        ("testInitString", testInitString),
        ("testLifetime", testLifetime),
        ("testName", testName),
        ("testOpen", testOpen),
        ("testPermissions", testPermissions),
        ("testReadWrite", testReadWrite),
    ]
}

extension PathTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathTests = [
        ("testAbsolutePath", testAbsolutePath),
        ("testAppending", testAppending),
        ("testAppendingMany", testAppendingMany),
        ("testDeletingLastComponent", testDeletingLastComponent),
        ("testDescription", testDescription),
        ("testExpandTilde", testExpandTilde),
        ("testRelativePath", testRelativePath),
        ("testString", testString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DirectoryTests.__allTests__DirectoryTests),
        testCase(FileLoggerTests.__allTests__FileLoggerTests),
        testCase(FileTests.__allTests__FileTests),
        testCase(PathTests.__allTests__PathTests),
    ]
}
#endif
